"project_id": "462614"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "lib/l10n/app_en.arb",
    "translation": "lib/l10n/app_%locale%.arb",
    "dest": "app_en.arb",
    "type": "arb",
  },
]
