name: Flutter Check Format

on:  
  pull_request: {}
  push: {}

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Check Dart Format
        run: dart format --set-exit-if-changed .